Create bmetric.eno pattern
ghostery/trackerdb pull request #395
Opened 2024-07-19 08:14 UTC by david-bmetric

Created bmetric pattern and added details

2024-07-19 08:15 UTC, david-bmetric commented
I've just added the pattern file with the hope that it can be added to Ghosterys database and that bmetric's script won't be displayed as unknown.

2024-07-19 13:05 UTC, philipp-classen commented
Thank you for the pull request. Do you have some examples websites where these requests are being sent? To get a better understanding of the impact of blocking them.

Also, I wonder if the pattern would not rather be Site Analytics (see https://github.com/ghostery/trackerdb/blob/main/docs/categories.md)? But I have no more context, so I'm guessing.

2024-07-21 23:16 UTC, david-bmetric commented
Hi @philipp-classen, thanks for your feedback, knowing our product well i think that Customer management fits quite well :). 

Some of our where you can see the script in action are: 
https://tryg.com/en
https://yousee.dk
https://www.telia.dk/

Our own website: https://bmetric.com/ where you can also learn more

Let me know if you have any ore questions :)

2024-07-23 16:28 UTC, philipp-classen requested changes

2024-07-23 16:28 UTC, philipp-classen commented on db/patterns/bmetric.eno
> +
```suggestion

```

2024-07-23 16:28 UTC, philipp-classen commented on db/patterns/bmetric.eno
> +
```suggestion

```

2024-07-23 16:28 UTC, philipp-classen commented on db/patterns/bmetric.eno
> +
```suggestion

```

2024-07-23 16:28 UTC, philipp-classen commented on db/patterns/bmetric.eno
> +
```suggestion

```

2024-07-23 16:30 UTC, philipp-classen approved these changes

2024-07-23 16:32 UTC, philipp-classen commented
Thank you!

FYI: I removed some blank lines, which broke the tests, and fixed a typo in the organization file.

2024-07-23 16:33 UTC, merged